<a href="https://colab.research.google.com/github/gadashriram/v-sigma-it-labs/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])


arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# 3d arry
arr3d = np.zeros((3, 3, 3))  
print(arr3d)
print(arr2d)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1 2 3]
 [4 5 6]]


In [2]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  
print(arr.ndim)   
print(arr.size)   
print(arr.dtype)  


(2, 3)
2
6
int64


In [3]:


arr = np.array([1, 2, 3, 4, 5])

print(arr[0])       # first element
print(arr[-1])      # last element
print(arr[1:4])     # array from index 1 to 4
print(arr[::-1])    # Reverse array


1
5
[2 3 4]
[5 4 3 2 1]


In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)     
print(arr1 * 2)        
print(np.dot(arr1, arr2))  


[5 7 9]
[2 4 6]
32
