<a href="https://colab.research.google.com/github/gadashriram/v-sigma-it-labs/blob/main/numpy/numpy-array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])


arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# 3d arry
arr3d = np.zeros((3, 3, 3))  
print(arr3d)
print(arr2d)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1 2 3]
 [4 5 6]]


In [4]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # Prints the shape of the array
print(arr.ndim)   # Prints the number of dimensions (2 in this case)
print(arr.size)   # Prints the total number of elements in the array
print(arr.dtype)  # Prints the data type of the array elements


(2, 3)
2
6
int64
